version: "3.7"
services:
  api-service:
    image: spring-boot-mongodb-docker-compose
    build: .
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - api-database
  api-database:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017